name: Formatter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "37 20 * * 3"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install formatter dependencies
        run: python -m pip install --editable ".[dev]"

      - name: Check Black formatting
        run: black --check --verbose .

      - name: Check import ordering
        run: isort --check-only --diff .
